#!/bin/sh
#/etc/init.d/lampService
### BEGIN INIT INFO
# Provides:          light.js
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start bluetooth program at boot time
# Description:       Enable bluetooth for the lamp.
### END INIT INFO
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
exec sudo forever --sourceDir=/home/pi/light -p /home/pi/light light.js
;;
stop)
exec sudo forever stop --sourceDir=/home/pi/light light.js
;;
*)
echo "Usage: /etc/init.d/lampService {start|stop}"
exit 1
;;
esac
exit 0


